# Generated by Django 3.0.5 on 2020-04-23 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('room', models.IntegerField(null=True)),
                ('backName', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('presentations', models.IntegerField()),
                ('interruptions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('name', models.CharField(max_length=200)),
                ('visitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('poi_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='museum.PointOfInterest')),
                ('visitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.TimeField()),
                ('name', models.CharField(max_length=300)),
                ('visitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Visitor')),
            ],
        ),
    ]
