# Generated by Django 3.0.5 on 2020-04-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('room', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('backName', models.CharField(max_length=100, null=True)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('blind', models.CharField(max_length=50)),
                ('headPhones', models.BooleanField()),
                ('notes', models.TextField()),
                ('defect', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='museum.Group')),
            ],
        ),
    ]
