# Generated by Django 3.0.5 on 2020-04-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_auto_20200410_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='endTime',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='startTime',
            field=models.CharField(max_length=30),
        ),
    ]
