# Generated by Django 3.0.5 on 2020-04-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_auto_20200410_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='number',
            field=models.IntegerField(),
        ),
    ]
